# Generated by Django 4.0.2 on 2023-04-09 09:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='image',
            field=models.ImageField(upload_to='word_images/'),
        ),
        migrations.AlterField(
            model_name='words',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
