# Generated by Django 4.0.2 on 2023-04-10 08:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_words_image_alter_words_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
