# Generated by Django 4.0.2 on 2023-04-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_words_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='word_images/'),
        ),
    ]
